spring:
  profiles: dev
  application:
    name: config-client-dev
server:
  port: 8888
---
spring:
  profiles: test
  application:
    name: config-client-test
server:
  port: 8080
---
spring:
  profiles: prod
  application:
    name: config-client-prod
server:
  port: 8088